server:
  port: 8080
spring:
  application:
    name: consul-provider-service
  config:
    import: consul://localhost:8500
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}
        serviceName: ${spring.application.name}
        healthCheckEnabled: true
      config:
        enabled: true # 开启consul
        prefix: config  # 设置配置的基本文件夹，默认config
        default-context: consul # 设置应用的文件夹名称，默认值application
        profile-separator: '-' # 环境分隔符，默认","
        format: YAML  # 指定配置文件格式
        data-key: consul-demo # 对应的配置文件名
        watch:
          enabled: true # 开启自动刷新，默认true
          delay: 1000 # 刷新频率，毫秒  默认1000